version: '3'

services:
  app:
    image: crud_eru
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - mongo


  db:
    image: mongo:latest
    ports:
      - "27017:27017"
